import { CATEGORY_LABELS } from "./issue-registry";
import type { SiteAuditResult } from "./types";

export function generateMarkdownReport(audit: SiteAuditResult): string {
  const s = audit.scores;
  const lines: string[] = [];

  lines.push(`# SEO Audit Report — ${audit.domain}`);
  lines.push("");
  lines.push(`- **URL:** ${audit.startUrl}`);
  lines.push(`- **Audited:** ${new Date(audit.crawledAt).toUTCString()}`);
  lines.push(`- **Pages crawled:** ${audit.pages.length}`);
  lines.push(`- **Duration:** ${(audit.durationMs / 1000).toFixed(1)}s`);
  lines.push("");
  lines.push(`## Overall Score: ${s.overall}/100 (Grade ${s.grade})`);
  lines.push("");
  lines.push(`| Category | Score |`);
  lines.push(`|---|---|`);
  for (const c of s.categories) {
    lines.push(`| ${c.label} | ${c.score}/100 |`);
  }
  lines.push("");
  lines.push(
    `**Issues found:** ${s.critical} critical · ${s.warning} warnings · ${s.info} info`,
  );
  lines.push("");

  // issue details grouped by category
  lines.push(`## Issues by Category`);
  const byCat = new Map<string, typeof audit.issues>();
  for (const issue of audit.issues) {
    byCat.set(issue.category, [...(byCat.get(issue.category) ?? []), issue]);
  }
  for (const [cat, issues] of byCat) {
    lines.push("");
    lines.push(`### ${CATEGORY_LABELS[cat] ?? cat} (${issues.length})`);
    for (const issue of issues) {
      lines.push("");
      lines.push(`#### [${issue.severity.toUpperCase()}] ${issue.title}`);
      if (issue.pageUrl) lines.push(`- **Page:** ${issue.pageUrl}`);
      if (issue.detail) lines.push(`- **Detail:** ${issue.detail}`);
      const desc = ISSUE_DESC[issue.issueId];
      if (desc) {
        lines.push(`- **Why it matters:** ${desc.explanation}`);
        lines.push(`- **How to fix:** ${desc.howToFix}`);
      }
    }
  }

  // page table
  lines.push("");
  lines.push(`## Crawled Pages`);
  lines.push("");
  lines.push(`| URL | Status | Title | Words | Time (ms) |`);
  lines.push(`|---|---|---|---|---|`);
  for (const p of audit.pages) {
    lines.push(
      `| ${p.meta.finalUrl.slice(0, 80)} | ${p.meta.status} | ${(p.title ?? "—").slice(0, 50)} | ${p.wordCount} | ${p.meta.responseTimeMs} |`,
    );
  }

  lines.push("");
  lines.push("---");
  lines.push(
    `*Generated by SEO Autopilot — ${new Date().toISOString()}*`,
  );

  return lines.join("\n");
}

// lazy import indirection to avoid circular import cost
import { ISSUE_REGISTRY as ISSUE_DESC } from "./issue-registry";
